### ISSUE TITLE
v2

### ISSUE THREAD

**Issue by kvz** [transloadit/eslint-config-transloadit#3]
Let's add rules here that we have second thoughts about. 

- [ ] Disable react/jsx-one-expression-per-line (https://github.com/transloadit/transloadit-api2/pull/2421#discussion_r616611886)

**Comment by mifi** [comment]
I think the React Hooks linting rules never made it in v1. It's an invaluable set of rules for preventing bugs in modern React using hooks.

Can be enabled by changing `extends` to `["airbnb", "airbnb/hooks"]`
https://github.com/transloadit/eslint-config-transloadit/blob/2d52b0f69daf28bfcd39b99f1f8ea1bffa72cfd9/index.js#L3

See https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb#eslint-config-airbnbhooks

**Comment by kvz** [comment]
+1, React hooks is a blind-spot for me, have no knowledge of it, will follow your judgement :ok_hand:

**Comment by juliangruber** [comment]
+100 to adding the hooks dependencies rule, as mentioned in the PR review ☝️

**Comment by mifi** [comment]
I added hooks now. Shall we release a new version v2 with this so we can start to use it in our repos?

**Comment by kvz** [comment]
I wonder if we should use the major to bundle more with it, what about:

- Disable react/jsx-one-expression-per-line?

We could also scan our biggest X project's `.eslintrc.js` files and check for overlapping `we're actually okay with these` sections, and consider adding those to our linting standard instead of having exceptions in all repos

**Comment by mifi** [comment]
Sure. Shall we write on slack and ask if anyone has some annoying eslint rules they had enough of, and they would like removed?

Oh btw disabling rules is not really a breaking change though? So that can be done at any time for a patch/minor version too?

**Comment by juliangruber** [comment]
+1 on disabling rules without a breaking change. To me it would only be breaking if previously passing code would afterwards fail.

**Comment by kvz** [comment]
that is a fair point yes!

**Comment by kvz** [comment]
:+1: will ask if anyone has gripes

**Comment by mifi** [comment]
So the things that we could include in this v2 is:
- whether anyone knows about some hip new eslint rules that should be added to our ruleset that would improve our coding
- maybe upgrade the upstream airbnb eslint dependency to get their latest and greatest rules
- whether some of the currently disabled rules should be re-enabled https://github.com/transloadit/eslint-config-transloadit/blob/9646317595bed16aa96bf61ab22d28528a8fb276/index.js#L56

**Comment by juliangruber** [comment]
I'm +1 for enabling

- max-classes-per-file
- one-var
- no-restricted-syntax
  - ForInStatement
  - LabeledStatement
  - WithStatement

I haven't evaluated yet how much work this would be

**Comment by kvz** [comment]
> I haven't evaluated yet how much work this would be

the escape there is letting the projects override to being a `warn`, and then making the respective refactoring & removal of `warn` overrides as separate pushes

**Comment by mifi** [comment]
I'm very for enabling as many rules as we want here (regardless how hard it is to fix those in all the projects) and then disable the rules (or set them as warn) in all the projects. That way as many projects as possible can take advantage of as many rules as possible from the central eslint-config-transloadit ruleset.

> * one-var

+1

> * no-restricted-syntax
>   
>   * ForInStatement
>   * LabeledStatement
>   * WithStatement

You want to **allow** or **disallow** these? Afaik there are already disallowed: https://github.com/transloadit/eslint-config-transloadit/blob/9646317595bed16aa96bf61ab22d28528a8fb276/index.js#L60

In addition, I would like to propose these changes:

- Remove this line (same as default from airbnb): https://github.com/transloadit/eslint-config-transloadit/blob/9646317595bed16aa96bf61ab22d28528a8fb276/index.js#L78

- change to error: https://github.com/transloadit/eslint-config-transloadit/blob/9646317595bed16aa96bf61ab22d28528a8fb276/index.js#L36

- Enable this? https://github.com/transloadit/eslint-config-transloadit/blob/9646317595bed16aa96bf61ab22d28528a8fb276/index.js#L59

- always-multiline? (or remove it to inherit from the [upstream rule](https://github.com/airbnb/javascript/blob/37d48dbf6082bd8958fdc5db5df207bb1166d653/packages/eslint-config-airbnb-base/rules/style.js#L42)) https://github.com/transloadit/eslint-config-transloadit/blob/9646317595bed16aa96bf61ab22d28528a8fb276/index.js#L125

- Enable this? can prevent mistakes if accidentally typing `=` instead of `==` (individual lines can be eslint-disabled where code is needed like `(match = x.match())`) https://github.com/transloadit/eslint-config-transloadit/blob/9646317595bed16aa96bf61ab22d28528a8fb276/index.js#L140

- Can remove this as it is already enabled upstream? https://github.com/transloadit/eslint-config-transloadit/blob/9646317595bed16aa96bf61ab22d28528a8fb276/index.js#L149
  https://github.com/airbnb/javascript/blob/37d48dbf6082bd8958fdc5db5df207bb1166d653/packages/eslint-config-airbnb-base/rules/style.js#L427

**Comment by juliangruber** [comment]
> You want to **allow** or **disallow** these? Afaik they are already disallowed:

I misread, I want to disallow as much restricted syntax as possible.

> * Remove this line (same as default from airbnb):

+1

> * change to error:

(no-unreachable-loop) +1

> * Enable this?

(no-underscore-dangle) +1 for variables, but -1 for anything on a class

> * always-multiline? (or remove it to inherit from the [upstream rule](https://github.com/airbnb/javascript/blob/37d48dbf6082bd8958fdc5db5df207bb1166d653/packages/eslint-config-airbnb-base/rules/style.js#L42))

(comma-dangle) Why didn't we do that already, for functions?

> * Enable this? can prevent mistakes if accidentally typing `=` instead of `==` (individual lines can be eslint-disabled where code is needed like `(match = x.match())`)

+-0

**Comment by mifi** [comment]
> > You want to **allow** or **disallow** these? Afaik they are already disallowed:
> 
> I misread, I want to disallow as much restricted syntax as possible.
> 
> >

Ah so you want to also disallow `ForOfStatement`. IMO sometimes it can be useful to do await inside a for of, instead of using pMap with concurrency=1, but I'm not religious about that and I do see disadvantages of for-loops.

> (no-underscore-dangle) +1 for variables, but -1 for anything on a class
> 
> >

Now that js classes support private `#method`, I'm not sure why we need underscores in classes, but it may be a too big change for some who are used to writing underscore.

> (comma-dangle) Why didn't we do that already, for functions?
> 
> >

The commit https://github.com/transloadit/eslint-config-transloadit/commit/d110589774b693aee42139d7581111e7cfcb0c8c doesn't say anything about why, maybe @kvz can elaborate

**Comment by juliangruber** [comment]
> Ah so you want to also disallow `ForOfStatement`. IMO sometimes it can be useful to do await inside a for of, instead of using pMap with concurrency=1, but I'm not religious about that and I do see disadvantages of for-loops.

I don't follow, sorry. I want do disallow `for in`, and keep `for of`. And I didn't mention await inside loop. I personally would like to be able to `await` inside a loop, without disabling the rule, but I can see how this can be useful for less experienced js devs.

> Now that js classes support private `#method`, I'm not sure why we need underscores in classes, but it may be a too big change for some who are used to writing underscore.

Right, we can use that now! Then I'm +1 for disallowing `_method`. There will be a lot of code changes also because of lodash, which is currently commonly imported as

```js
const _map = require('lodash/map')
```

**Comment by mifi** [comment]
> I don't follow, sorry. I want do disallow `for in`, and keep `for of`. And I didn't mention await inside loop. I personally would like to be able to `await` inside a loop, without disabling the rule, but I can see how this can be useful for less experienced js devs.
> 
> >

Ah, yes I just meant that sometimes I write code like this to run an async operation on an array in series:
```js
for (const val of array) {
  await runSomething(val);
}
```
if we disallow for-of I can no longer write that code, but instead have to write something like:
```js
const pMap = require('p-map');
await pMap(array, runSomething, { concurrency: 1 });
```
...which I am also fine with.

> Right, we can use that now! Then I'm +1 for disallowing `_method`. There will be a lot of code changes also because of lodash, which is currently commonly imported as

I think it's gonna be a lot of code violating that rule too in some projects, but we can just disable this rule in these projects, but keep it enabled in eslint-config-transloadit

**Comment by juliangruber** [comment]
> ...which I am also fine with.

Sorry, I didn't say anywhere that I want to disallow for-of, which would be a terrible choice for me

**Comment by mifi** [comment]
> Sorry, I didn't say anywhere that I want to disallow for-of, which would be a terrible choice for me

oops sorry I misread you then! `for-in` is already disallowed. Currently disallowed statemenets are: ForInStatement, LabeledStatement and WithStatement. Which ones do you want to disallow/allow relative to this?

**Comment by juliangruber** [comment]
> oops sorry I misread you then! `for-in` is already disallowed. Currently disallowed statemenets are: ForInStatement, LabeledStatement and WithStatement. Which ones do you want to disallow/allow relative to this?

No worries, if we disallow the default set of statements that should be fine

**Comment by mifi** [comment]
@aduh95 suggested these two changes:
```
'no-await-in-loop': 'off',
'object-shorthand': ['error', 'always'],
```

Anyone else have opinions about those?

`object-shorthand` seems to be already set from airbnb to:
```js
    'object-shorthand': ['error', 'always', {
      ignoreConstructors: false,
      avoidQuotes: true,
    }],
```
so I guess that's fine, or do you have any strong reason to remove `ignoreConstructors: false` or `avoidQuotes: true`?

The argument for keeping `no-await-in-loop` enabled is to discourage developers from writing code that performs slower, because if we use a for-loop with await on each item it will process the items in series. Often async operations on elements in an array don't depend on eachother and can be run in parallel (with something like pMap) which could be much faster. See https://eslint.org/docs/rules/no-await-in-loop

Shall I do all the changes we agreed upon and then release a v2?

**Comment by juliangruber** [comment]
> 'object-shorthand': ['error', 'always'],

+1

> The argument for keeping `no-await-in-loop` enabled is to discourage developers from writing code that performs slower, because if we use a for-loop with await on each item it will process the items in series. Often async operations on elements in an array don't depend on eachother and can be run in parallel (with something like pMap) which could be much faster. See https://eslint.org/docs/rules/no-await-in-loop

I'm +-0 on this, it's a bit annoying that you have to disable a rule although you write perfectly correct and performant code. If you know what you're doing.

**Comment by juliangruber** [comment]
Let's disable it and see if it bites us?

**Comment by mifi** [comment]
Created a PR for more v2 changes: #12
